name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env: 
         working-directory: ./Testing

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
         sudo apt-get -y install torch torchvision numpy math
        sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev 
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
      working-directory: ${{env.working-directory}}
