name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env: 
         working-directory: ./Implementation

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies 
      run: |
        pip install pylint torch torchvision numpy matplotlib h5py
        python -m pip install --upgrade pip
    - name: Analysing the code with pylint
      run: |
        pylint `ls -R|grep .py$|xargs`
      working-directory: ${{env.working-directory}}
